#!/bin/bash

export RCROOTADDRESS=$1
echo $RCROOTADDRESS
export RCTESTUSER=$2
echo $RCTESTUSER
export RCTESTPASSWORD=$3
echo $RCTESTPASSWORD
export REFUND_TRANSACTION=$4
echo $REFUND_TRANSACTION
export REFUND_ADDRESS=$5
echo $REFUND_ADDRESS
